"""User table add phone

Revision ID: 46b8f2ff5520
Revises: 74bca4d0ada6
Create Date: 2020-04-25 12:38:35.128664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b8f2ff5520'
down_revision = '74bca4d0ada6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
