"""many-many between book and author

Revision ID: 91229b173ac7
Revises: ee0e50dae531
Create Date: 2020-04-25 16:22:03.468095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91229b173ac7'
down_revision = 'ee0e50dae531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_author',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], )
    )
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'])
    op.drop_table('book_author')
    # ### end Alembic commands ###
